### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by TimGoll** [Valerate/SimpleOreSamples#2] opened 2018-10-10 15:51 UTC
forge-1.12.2-14.23.4.2760
SimpleOreSamples-1.12-1.1

https://gist.github.com/TimGoll/89321f577bfe33da61966fa83c6a010e

I haven't edited the config file

**Comment by TimGoll** [comment] 2018-10-10 15:55
okay. I fixed the problem by myself!

`I:"Amount of ores to create a surface sample"` your number did not match the number of the ores

**Comment by ghost** [comment] 2018-10-20 13:13
I have the same problem and I can't start the game now. I've tried to change that setting in config but don't know what I should put there to make it work.

**Comment by TimGoll** [comment] 2018-10-20 13:14
Count the amount of entries in the array (between the `<` and `>`) and set the number in one of the first lines to the amount

**Comment by gctypo** [comment] 2018-10-31 01:28
The fix does not seem to work for me. 21 entries within `Ores samples`, but setting `Amount of ores to create a surface sample` to 21 does not prevent the crash.

**Comment by Valerate** [comment] 2018-10-31 04:33
Hi,

What does your config look like, I'm not entirely sure what causes it
And what other mods do you guys have that adds ores? There might be some incompatabilities.
The config option you guys are talking about is just counting the amount of ores in an chunk and dividing it on the amount you have configures to determine the amount of samples it is to generate.


And please post your errors guys, I dont know how to track it down without one. The error the OP's post complains about this line `	else if (OreDictionary.doesOreNameExist(dropType+"Aluminum")) ` and I dont know how that causes and arrayoutofbounds limit

**Comment by TimGoll** [comment] 2018-10-31 06:28
No, the error out of bounds is caused because you have a config option for the array size. And this config option is different to the size of the actual array.  

@gctypo you should definitely post your crashlog.

**Comment by Valerate** [comment] 2018-10-31 06:39
In what way do I have a config option for an array size? None of the options in the config file is used to generate an array, they are all used as ints to decrement to the amount of ores to create;

`int oreSamplesToCreate = Config.oreCounterEnabled ? COUNTER.get(ore)/Config.oresPerSample : Config.samplesPerOrePerChunk;`

and

`for (int i = 0;  i < Math.random()*Math.min(Config.samplesPerOrePerChunk,oreSamplesToCreate)+1 ;i++) {`

**Comment by TimGoll** [comment] 2018-10-31 06:48
Okay strange. But the above mentioned config option fixed the bug for me 

Edit: it only fixed it after I had changed it to the amount of values in the array

**Comment by Valerate** [comment] 2018-11-02 13:55
I just cant reproduce the issue you guys are having, can you atleast show me the config file so I can see what you have done?

**Comment by TimGoll** [comment] 2018-11-02 13:56
I haven't changed anything. I downloaded the mod and had this issue. Later on I changed the one line to make it work

**Comment by Valerate** [comment] 2018-11-02 14:40
Hopefully fixed in V1.2

**Closed as completed by Valerate** 2018-11-02 14:40 UTC
